<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
    <PackageReference Include="FluentValidation" Version="8.2.2" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="8.2.2" />
    <PackageReference Include="MediatR" Version="8.0.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.10" />
</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\AppointmentManagementSystem.Domain\AppointmentManagementSystem.Domain.csproj" />
	</ItemGroup>

</Project>