<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="8.2.2" />
		<PackageReference Include="MediatR" Version="8.0.0" />
		<PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Options" Version="10.0.10" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\AppointmentManagementSystem.Application\AppointmentManagementSystem.Application.csproj" />
		<ProjectReference Include="..\AppointmentManagementSystem.Domain\AppointmentManagementSystem.Domain.csproj" />
	</ItemGroup>

</Project>