<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="NewFolder\**" />
	  <Content Remove="NewFolder\**" />
	  <EmbeddedResource Remove="NewFolder\**" />
	  <None Remove="NewFolder\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="8.2.2" />
		<PackageReference Include="MediatR" Version="8.0.0" />
		<PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Options" Version="10.0.10" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\AppointmentManagementSystem.Application\AppointmentManagementSystem.Application.csproj" />
		<ProjectReference Include="..\AppointmentManagementSystem.Infrastructure\AppointmentManagementSystem.Infrastructure.csproj" />
		<ProjectReference Include="..\AppointmentManagementSystem.Persistence\AppointmentManagementSystem.Persistence.csproj" />
	</ItemGroup>

</Project>